name: Build and Deploy to S3

on:
  push:
    branches:
      - main 
      - develop
      - staging
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Upload to S3
        run: |
          aws s3 sync ./dist/apps/catalog s3://${{ vars.AWS_S3_BUCKET_NAME }}
        env:
          AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET_NAME }} 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }} 
          AWS_REGION: us-east-1
          SOURCE_DIR: dist  
          
  sonarcloud:
    name: SonarQube Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  
      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


